SELECT COUNT(*) AS FISH_COUNT
FROM FISH_INFO AS F
WHERE F.FISH_TYPE = (SELECT FISH_TYPE
                    FROM FISH_NAME_INFO
                    WHERE FISH_NAME='BASS') OR
      F.FISH_TYPE = (SELECT FISH_TYPE
                    FROM FISH_NAME_INFO
                    WHERE FISH_NAME='SNAPPER')
